# Konfigurasi Nginx untuk menyajikan aplikasi React (SPA)
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Semua rute diarahkan ke index.html (React Router / SPA fallback)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
